(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], KEY='bbq-static:';
let deferredInstallPrompt=null;
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(KEY+k))??f}catch{return f}}, save=(k,v)=>localStorage.setItem(KEY+k,JSON.stringify(v));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
let state={screen:'home',history:load('history',[]),wishes:load('wishes',[]),reports:load('reports',[]),wealth:load('wealth',[]),streak:load('streak',0),worshipDates:load('worshipDates',[]),settings:load('settings',{sound:true,motion:true}),currentRecord:null,fortuneCategory:'財運',bookFilter:'全部',wishCategory:'財運',mood:'平靜',checks:{boundaries:false,promise:false,facedIt:false},worshipStep:0};
const messages=['今天不用證明自己給所有人看，先把真正重要的事情做好。','妳可以慢一點，但別把真正想去的地方弄丟。','看清局，再選路。焦慮不替妳做決定。','把力氣留給值得的人、值得的事，還有值得的妳自己。','今天若很累，就先完成最重要的一件事。剩下的，明天再打。'];
const daily=messages[new Date().getDate()%messages.length];
function persist(){save('history',state.history);save('wishes',state.wishes);save('reports',state.reports);save('wealth',state.wealth);save('streak',state.streak);save('worshipDates',state.worshipDates);save('settings',state.settings)}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2200)}
function show(name){state.screen=name;$$('.screen').forEach(x=>x.classList.toggle('active',x.id===name));$('#backBtn').classList.toggle('hidden',['home','rituals','queen','messages','profile'].includes(name));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===(['worship','fortune','fortune-result','book','wishes','report','wealth'].includes(name)?'rituals':name)));window.scrollTo({top:0,behavior:state.settings.motion?'smooth':'auto'});render(name)}
function render(name){if(name==='home')renderHome();if(name==='profile')renderProfile();if(name==='messages')renderMessages();if(name==='fortune')renderFortune();if(name==='fortune-result')renderResult();if(name==='book')renderBook();if(name==='wishes')renderWishes();if(name==='report')renderReport();if(name==='wealth')renderWealth();if(name==='worship')renderWorship();if(name==='queen')$('#queenDaily').textContent=daily}
function renderHome(){const done=state.worshipDates.includes(today());$('#worshipState').textContent=done?'今日已參拜':'點燈・靜心';$('#streakValue').textContent=state.streak;$('#dailyMessage').textContent=daily;$('#moonPhases').innerHTML=Array.from({length:7},(_,i)=>`<i class="${i<Math.min(7,state.streak)?'on':''}"></i>`).join('')}
function renderMessages(){const list=[['今天的信','妳不需要一次把整座山搬走。今天搬一塊石頭就好。','今日'],['夜裡記得回來','如果今天被外面的聲音弄得很亂，回殿裡坐一下。','昨日'],['關於妳的願望','願望不是拿來逼迫自己的鞭子。它應該是一個方向。','09/13']];$('#letterList').innerHTML=list.map(x=>`<article class="letter"><small>${x[2]}</small><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}
function renderProfile(){const completed=state.wishes.filter(w=>w.status==='已實現').length,favs=state.history.filter(h=>h.favorite).length;$('#stats').innerHTML=[[state.streak,'連續天數'],[state.worshipDates.length,'參拜'],[state.history.length,'籤詩'],[completed,'實現願望'],[favs,'收藏']].map(x=>`<div class="stat"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('');$('#soundToggle').checked=state.settings.sound;$('#motionToggle').checked=state.settings.motion}
function renderWorship(){const steps=['入殿靜心','點亮紫月燈','獻上一炷香','寫下今日心願','向女王行禮'];const already=state.worshipDates.includes(today());if(already&&state.worshipStep===0)state.worshipStep=steps.length;$('#worshipSteps').innerHTML=steps.map((s,i)=>`<div class="step ${i<state.worshipStep?'done':i===state.worshipStep?'active':''}"><i>${i<state.worshipStep?'✓':i+1}</i><span>${s}</span></div>`).join('');$('#altarFlame').classList.toggle('on',state.worshipStep>=2);$('#altarSmoke').classList.toggle('on',state.worshipStep>=3);$('#worshipWish').classList.toggle('hidden',state.worshipStep!==3);const btn=$('#worshipNext');if(state.worshipStep>=steps.length){btn.textContent=already?'今日已參拜・回首頁':'完成參拜・回首頁'}else btn.textContent=['進入主殿','點亮紫月燈','獻香','收下心願','完成參拜'][state.worshipStep]}
function nextWorship(){const max=5;if(state.worshipStep<max){state.worshipStep++;renderWorship();return}if(!state.worshipDates.includes(today())){state.worshipDates.push(today());state.streak++;persist();toast('今日參拜完成。女王把妳的心願收好了。')}state.worshipStep=0;show('home')}
function renderFortune(){const cats=window.FORTUNE_CATEGORIES;$('#fortuneCats').innerHTML=cats.map(c=>`<button data-cat="${c}" class="${c===state.fortuneCategory?'active':''}">${c}</button>`).join('');$$('#fortuneCats button').forEach(b=>b.onclick=()=>{state.fortuneCategory=b.dataset.cat;renderFortune()});const ex=state.history.find(h=>h.date===today()&&h.category===state.fortuneCategory);$('#existingFortune').classList.toggle('hidden',!ex);$('#existingFortune').textContent=ex?`妳今天已經正式問過「${state.fortuneCategory}」了。再次點擊會回看今日籤。`:'';$('#drawFortune').textContent=ex?'查看今日正式籤':'開始抽籤'}
function drawFortune(){const ex=state.history.find(h=>h.date===today()&&h.category===state.fortuneCategory);if(ex){state.currentRecord=ex;show('fortune-result');return}const tube=$('#fortuneTube');tube.classList.add('shake');setTimeout(()=>{tube.classList.remove('shake');const pool=window.FORTUNES.filter(f=>f.category===state.fortuneCategory);const f=pool[Math.floor(Math.random()*pool.length)];const rec={id:uid('draw'),date:today(),category:state.fortuneCategory,question:$('#fortuneQuestion').value.trim(),fortuneId:f.id,favorite:false};state.history.unshift(rec);state.currentRecord=rec;persist();show('fortune-result')},850)}
function fortuneById(id){return window.FORTUNES.find(f=>f.id===id)}
function renderResult(){const r=state.currentRecord||state.history[0];if(!r)return show('fortune');state.currentRecord=r;const f=fortuneById(r.fortuneId);$('#resultCard').innerHTML=`<div class="fortune-slip"><small>第 ${String(f.number).padStart(2,'0')} 籤</small><h1>${f.name}</h1><span class="level">${f.fortuneLevel}</span><div class="poem">${f.poemLines.map(x=>`<div>${x}</div>`).join('')}</div></div>${r.question?`<div class="panel"><h3>妳問</h3><p>「${r.question}」</p></div>`:''}<div class="panel"><h3>✦ 女王解籤</h3><p>${f.queenInterpretation}</p></div><div class="panel"><h3>現實建議</h3><ul>${f.realWorldAdvice.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="queen-quote">「${f.queenHugLine}」<br><small>— 黑蝠女王</small></div>`;$('#favBtn').textContent=r.favorite?'♥ 已收藏':'♡ 收藏'}
function toggleFav(){if(!state.currentRecord)return;const r=state.history.find(x=>x.id===state.currentRecord.id);if(r){r.favorite=!r.favorite;state.currentRecord=r;persist();renderResult()}}
function renderBook(){const fs=['全部','收藏',...window.FORTUNE_CATEGORIES];$('#bookFilters').innerHTML=fs.map(x=>`<button data-filter="${x}" class="${x===state.bookFilter?'active':''}">${x}</button>`).join('');$$('#bookFilters button').forEach(b=>b.onclick=()=>{state.bookFilter=b.dataset.filter;renderBook()});const list=state.history.filter(r=>state.bookFilter==='全部'||(state.bookFilter==='收藏'?r.favorite:r.category===state.bookFilter));$('#bookList').innerHTML=list.length?list.map(r=>{const f=fortuneById(r.fortuneId);return `<div class="record" data-id="${r.id}"><div class="record-num">${String(f.number).padStart(2,'0')}</div><div class="open-record"><small>${r.date} · ${r.category}</small><strong>${f.name}</strong><p>${f.poemLines[0]}，${f.poemLines[1]}。</p></div><button class="fav-record">${r.favorite?'♥':'♡'}</button></div>`}).join(''):'<div class="panel center">籤簿還是空的。抽過的正式籤會留在這裡。</div>';$$('.record').forEach(el=>{el.querySelector('.open-record').onclick=()=>{state.currentRecord=state.history.find(x=>x.id===el.dataset.id);show('fortune-result')};el.querySelector('.fav-record').onclick=()=>{const r=state.history.find(x=>x.id===el.dataset.id);r.favorite=!r.favorite;persist();renderBook()}})}
function renderWishes(){const cats=['財運','事業','感情','平安','破局','其他'];$('#wishCats').innerHTML=cats.map(c=>`<button data-wcat="${c}" class="${c===state.wishCategory?'active':''}">${c}</button>`).join('');$$('#wishCats button').forEach(b=>b.onclick=()=>{state.wishCategory=b.dataset.wcat;renderWishes()});$('#wishList').innerHTML=state.wishes.length?state.wishes.map(w=>`<div class="wish" data-id="${w.id}"><small>${w.category} · ${w.createdAt.slice(0,10)}</small><p>${w.content}</p><select><option ${w.status==='祈願中'?'selected':''}>祈願中</option><option ${w.status==='已實現'?'selected':''}>已實現</option><option ${w.status==='放下'?'selected':''}>放下</option></select></div>`).join(''):'<div class="panel center">還沒有願望。第一個願望，寫給真正想成為的自己。</div>';$$('.wish select').forEach(s=>s.onchange=()=>{const w=state.wishes.find(x=>x.id===s.closest('.wish').dataset.id);w.status=s.value;persist()})}
function sendWish(){const text=$('#wishText').value.trim();if(!text)return toast('先寫下妳真正想說的願望。');state.wishes.unshift({id:uid('wish'),category:state.wishCategory,content:text,status:'祈願中',createdAt:new Date().toISOString()});$('#wishText').value='';persist();toast('本王聽見了。');renderWishes()}
function renderReport(){const ex=state.reports.find(r=>r.date===today());if(ex){state.checks={boundaries:ex.boundaries,promise:ex.promise,facedIt:ex.facedIt};state.mood=ex.mood;$('#proudOf').value=ex.proudOf||'';$('#reportNote').value=ex.note||''}$('#reportStreak').textContent=state.streak;const qs=[['boundaries','今天有沒有守住自己的界線？'],['promise','今天有沒有完成答應自己的事情？'],['facedIt','今天有沒有面對原本想逃避的事？']];$('#reportChecks').innerHTML=qs.map(x=>`<button class="check ${state.checks[x[0]]?'on':''}" data-check="${x[0]}"><i>${state.checks[x[0]]?'✓':''}</i><span>${x[1]}</span></button>`).join('');$$('#reportChecks .check').forEach(b=>b.onclick=()=>{state.checks[b.dataset.check]=!state.checks[b.dataset.check];renderReport()});const moods=['平靜','疲累','開心','焦躁','難過'];$('#moods').innerHTML=moods.map(m=>`<button data-mood="${m}" class="${m===state.mood?'active':''}">${m}</button>`).join('');$$('#moods button').forEach(b=>b.onclick=()=>{state.mood=b.dataset.mood;renderReport()});$('#reportReply').classList.toggle('hidden',!ex)}
function saveReport(){const ex=state.reports.find(r=>r.date===today());const r={date:today(),...state.checks,proudOf:$('#proudOf').value.trim(),mood:state.mood,note:$('#reportNote').value.trim()};if(ex)Object.assign(ex,r);else{state.reports.unshift(r);state.streak++}persist();$('#reportReply').classList.remove('hidden');$('#reportStreak').textContent=state.streak;toast('今晚覆命收好了。')}
function renderWealth(){$('#wealthList').innerHTML=state.wealth.map(a=>`<button class="wealth-action ${a.done?'on':''}" data-id="${a.id}"><i>${a.done?'✓':''}</i><span>${a.text}</span></button>`).join('');$$('.wealth-action').forEach(b=>b.onclick=()=>{const a=state.wealth.find(x=>x.id===b.dataset.id);a.done=!a.done;persist();renderWealth()})}
function addWealth(){const text=$('#wealthInput').value.trim();if(!text)return;state.wealth.unshift({id:uid('wealth'),text,done:false,createdAt:new Date().toISOString()});$('#wealthInput').value='';persist();renderWealth()}
function hug(open){$('#hugOverlay').classList.toggle('hidden',!open)}
function initWelcome(){const seen=localStorage.getItem(KEY+'welcomeSeen');if(!seen)$('#welcomeOverlay').classList.remove('hidden');$('#enterShrine').onclick=()=>{localStorage.setItem(KEY+'welcomeSeen','1');$('#welcomeOverlay').classList.add('hidden')}}
function initInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').classList.remove('hidden');$('#moonMark').classList.add('hidden')});$('#installBtn').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice}catch{}deferredInstallPrompt=null;$('#installBtn').classList.add('hidden');$('#moonMark').classList.remove('hidden')};window.addEventListener('appinstalled',()=>{toast('黑蝠女王殿已安裝到這台裝置。');$('#installBtn').classList.add('hidden');$('#moonMark').classList.remove('hidden')})}
$$('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));$$('[data-action="hug"]').forEach(b=>b.onclick=()=>hug(true));$('#closeHug').onclick=$('#hugDone').onclick=()=>hug(false);$('#backBtn').onclick=()=>show('home');$('#worshipNext').onclick=nextWorship;$('#drawFortune').onclick=drawFortune;$('#favBtn').onclick=toggleFav;$('#sendWish').onclick=sendWish;$('#saveReport').onclick=saveReport;$('#addWealth').onclick=addWealth;$('#wealthFortune').onclick=()=>{state.fortuneCategory='財運';show('fortune')};$('#soundToggle').onchange=e=>{state.settings.sound=e.target.checked;persist()};$('#motionToggle').onchange=e=>{state.settings.motion=e.target.checked;document.body.classList.toggle('no-motion',!state.settings.motion);persist()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});document.body.classList.toggle('no-motion',!state.settings.motion);initWelcome();initInstall();show('home');
})();
