const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY='bbq-static:';
let deferredInstallPrompt=null;
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(KEY+k))??f}catch{return f}},save=(k,v)=>localStorage.setItem(KEY+k,JSON.stringify(v));
const today=()=>{let d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
let state={screen:'home',history:load('history',[]),wishes:load('wishes',[]),reports:load('reports',[]),wealth:load('wealth',[]),streak:load('streak',0),worshipDates:load('worshipDates',[]),settings:load('settings',{sound:true,motion:true}),currentRecord:null,fortuneCategory:'財運',bookFilter:'全部',wishCategory:'財運',mood:'平靜',checks:{boundaries:false,promise:false,facedIt:false},worshipStep:0};
const messages=['今天不用證明自己給所有人看，先把真正重要的事情做好。','妳可以慢一點，但別把真正想去的地方弄丟。','看清局，再選路。焦慮不替妳做決定。','把力氣留給值得的人、值得的事，還有值得的妳自己。','今天若很累，就先完成最重要的一件事。剩下的，明天再打。'],daily=messages[new Date().getDate()%messages.length];
function persist(){for(const k of ['history','wishes','reports','wealth','streak','worshipDates','settings'])save(k,state[k])}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2200)}
function show(name){state.screen=name;$$('.screen').forEach(x=>x.classList.toggle('active',x.id===name));$('#backBtn').classList.toggle('hidden',['home','rituals','queen','messages','profile'].includes(name));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===(['worship','fortune','fortune-result','book','wishes','report','wealth'].includes(name)?'rituals':name)));window.scrollTo({top:0,behavior:state.settings.motion?'smooth':'auto'});render(name)}
function render(n){if(n==='home')renderHome();if(n==='profile')renderProfile();if(n==='messages')renderMessages();if(n==='worship')renderWorship();if(n==='fortune')renderFortune();if(n==='fortune-result')renderResult();if(n==='book')renderBook();if(n==='wishes')renderWishes();if(n==='report')renderReport();if(n==='wealth')renderWealth();if(n==='queen')$('#queenDaily').textContent=daily}
function renderHome(){let done=state.worshipDates.includes(today());$('#worshipState').textContent=done?'今日已參拜':'向女王獻上心意';$('#streakValue').textContent=state.streak;$('#dailyMessage').textContent=daily;$('#moonPhases').innerHTML=Array.from({length:7},(_,i)=>`<i style="display:inline-block;width:10px;height:10px;border-radius:50%;margin:2px;background:${i<Math.min(7,state.streak)?'#cba2ff':'#43384d'}"></i>`).join('')}
function renderMessages(){let a=[['今天的信','妳不需要一次把整座山搬走。今天搬一塊石頭就好。','今日'],['夜裡記得回來','如果今天被外面的聲音弄得很亂，回殿裡坐一下。','昨日'],['關於妳的願望','願望不是拿來逼迫自己的鞭子。它應該是一個方向。','09/13']];$('#letterList').innerHTML=a.map(x=>`<article><small>${x[2]}</small><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}
function renderProfile(){let completed=state.wishes.filter(w=>w.status==='已實現').length,favs=state.history.filter(h=>h.favorite).length;$('#stats').innerHTML=[[state.streak,'連續天數'],[state.worshipDates.length,'參拜'],[state.history.length,'籤詩'],[completed,'實現願望'],[favs,'收藏']].map(x=>`<div class="stat"><strong>${x[0]}</strong><small>${x[1]}</small></div>`).join('');$('#soundToggle').checked=state.settings.sound;$('#motionToggle').checked=state.settings.motion}
function hug(open){$('#hugOverlay').classList.toggle('hidden',!open)}
